language: go
go:
 - 1.1
 - 1.2
 - 1.3
 - release
 - tip

script:
  # Add the go-getter script for depencencies.
 - wget https://raw.githubusercontent.com/joewalnes/go-getter/master/go-getter
 - chmod a+x go-getter
 - mv go-getter $HOME/bin
 # Run the test suite.
 - make test
